### PR TITLE
Dendrogram andrew tweaks

### PR DESCRIPTION
**Pull request by theengineear**
This is based off of @OxanaSachenkova 's branch, which added `Dendrogram` plots \o/\o/\o/

Todo:

- [x] version bump
- [x] changelog

### CODE REVIEW

**Comment by theengineear** [comment]
@OxanaSachenkova , I mostly did some re-arranging and I tried to strengthen the test suite by always checking the full objects that get returned from your code-paths.

Mind giving the tests a look to make sure they're as expected?

**Comment by theengineear** [comment]
@etpinard @chriddyp @cldougl this has been looked over a bunch and is going in as *beta* functionality. Think we can merge it in?

**Comment by chriddyp** [comment]
looks good to me! can you add whatever ipython notebook that you've been using to test-run this package to the documentation repo when it's merged? you'll just need to add one line to the end of the notebook that describes the URL, etc. See here for an example: https://github.com/plotly/documentation/blob/source/_posts/python/finance/candlestick-charts.ipynb

**Comment by OxanaSachenkova** [comment]
@chriddyp will do! just  need to polish it up a bit, quite messy right now

**Comment by theengineear** [comment]
Can we :dancer: on it?

**Comment by chriddyp** [comment]
:dancer:

**Comment by theengineear** [comment]
Thanks again @OxanaSachenkova !

**Comment by jackparmer** [comment]
Hey @cldougl Could add some dendrogram examples to the Python docs when you have some free time? I want to get these into next month's blog posts.

**Comment by cldougl** [comment]
@theengineear @chriddyp 
not sure the dendrograms are still embedding in notebooks correctly http://nbviewer.ipython.org/gist/cldougl/cfdffaf7b8b0185af552 (unless I'm doing something wrong but they're fine not embedded https://plot.ly/~chelsea_lyn/7664 ).

**Comment by chriddyp** [comment]
@cldougl - can you try moving the height and width into the layout and out
of `iplot`?

On Tue, Oct 20, 2015 at 3:46 PM, Chelsea <notifications@github.com> wrote:

> @theengineear <https://github.com/theengineear> @chriddyp
> <https://github.com/chriddyp>
> not sure the dendrograms are still embedding in notebooks correctly
> http://nbviewer.ipython.org/gist/cldougl/cfdffaf7b8b0185af552 (unless I'm
> doing something wrong but they're fine not embedded
> https://plot.ly/~chelsea_lyn/7664 ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.py/pull/312#issuecomment-149680847>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team

**Comment by cldougl** [comment]
yep that works- I'll update the examples in the docstring

**Pull request merged**
