### PR TITLE
Clean up error handling

### LINKED ISSUE #295: Revisit Error handling with the new graph objects setup.
Logging this to reference some skipped tests in dev.

The way we construct 'path' has gotten a bit smarter, so we could likely simplify the complicated way in which we return errors to users.

### PR DESCRIPTION
**Pull request by theengineear**
Fixes #295

todo:

- [x] stop using class names in errors
- [x] auto-add help to errors
- [x] simplify error creation

### CODE REVIEW

**Comment by theengineear** [comment]
@chriddyp and @etpinard ready for review. There was only one thing I wanted to keep backwards comptatible, which is the `plain_message` field. We actually use this in streambed...

**Comment by theengineear** [comment]
I'll wait until this gets the :dancer: to work on https://github.com/plotly/python-api/issues/289, which i'd like to do soonish.

**Comment by etpinard** [comment]
Looks good. :dancer:

**Comment by theengineear** [comment]
Cool gonna merge this in then and put in some time on enhancing docstrings.

**Pull request merged**
