### PR TITLE
check that secret graphs are accessible before returning them.

### PR DESCRIPTION
**Pull request by chriddyp**
if they aren't accessible, attempt to add the share key again

related to https://github.com/plotly/streambed/issues/4089

### CODE REVIEW

**Comment by chriddyp** [comment]
cc @BRONSOLO @theengineear @cldougl

**Comment by theengineear** [comment]
@chriddyp , I caught ya!

>AssertionError: The default, hard-coded plot schema we ship with pip is out of sync with the prod plot schema!
Run `make update_default_schema` to fix it!

Did that error make sense to you when you saw it? Looks like you sorted it out pretty quick.

**Comment by chriddyp** [comment]
@theengineear - yup, made sense!

**Comment by theengineear** [comment]
@chriddyp is this meant to be a permanent addition? If it's not, can we add a `TODO` in the code with a linked GH issue?

If this is just a temporary patch, it can :dancer: after it's been linked to an issue. I would assume this is a streambed bug, right?

**Comment by chriddyp** [comment]
yup, [streambed bug](https://github.com/plotly/streambed/issues/4089). OK, I added the link in that code block.

**Comment by theengineear** [comment]
:dancer:

**Comment by BRONSOLO** [comment]
:dancer:

**Pull request merged**
