### PR TITLE
candlestick with boxplots

### PR DESCRIPTION
**Pull request by cldougl**
- re
https://github.com/plotly/streambed/pull/3291#issuecomment-128185914 if
we want to use the box plot solution for candles this seems simpler
@jackparmer @chriddyp

### CODE REVIEW

**Comment by jackparmer** [comment]
+1

**Comment by theengineear** [comment]
:dancer: !

**Comment by chriddyp** [comment]
sweet! could you re-run the finance doc examples with this new version?

**Comment by cldougl** [comment]
yep!

**Pull request merged**
