### PR TITLE
Fix anaconda simplejson issue

### LINKED ISSUE #197: Installing simplejson kills pip on anaconda
@theengineear, from: http://stackoverflow.com/questions/28751216/plotly-killed-my-python-install?nah=1#28754036

Python 3.4 on Windows via Anaconda 2.1.0: installing simplejson (which is pulled in by Plotly's requirements.txt) kills pip:
```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\pip-script.py", line 3, in <module>
    from pip import main
  File "C:\Anaconda3\lib\site-packages\pip\__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Anaconda3\lib\site-packages\pip\download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\compat.py", line 77, in <module>
    import simplejson as json
  File "C:\Anaconda3\lib\site-packages\simplejson\__init__.py", line 112, in <module>
    from .scanner import JSONDecodeError
  File "C:\Anaconda3\lib\site-packages\simplejson\scanner.py", line 10, in <module>
    c_make_scanner = _import_c_make_scanner()
  File "C:\Anaconda3\lib\site-packages\simplejson\scanner.py", line 6, in _import_c_make_scanner
    from simplejson._speedups import make_scanner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```

Can we *not* install simplejson unless it's really needed (Python 2.6 systems)?  Or is there another way we can work around this Anaconda issue?  (Logged for Anaconda as: https://github.com/ContinuumIO/anaconda-issues/issues/238 )

### PR DESCRIPTION
**Pull request by theengineear**
Fixes #197 

We now have an `extras_require` mapping to optional dependencies for python 2.6

### CODE REVIEW

**Comment by theengineear** [comment]
You can test that it works by doing the following in a local copy of this repo (i couldn't get it to work from github)

```bash
pip install -e '.[PY2.6]'
```
```

**Comment by theengineear** [comment]
@etpinard and @scjody , seem like a reasonable solution?

**Comment by etpinard** [comment]
I like it. :dancer:

**Comment by theengineear** [comment]
The normal workflow I'm expecting is this (/dev/null just for brevity below):

```
$ pip install plotly > /dev/null
$ python -c 'import plotly'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "plotly/__init__.py", line 31, in <module>
    from plotly import plotly, graph_objs, grid_objs, tools, utils, session
  File "plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "plotly/plotly/plotly.py", line 35, in <module>
    from plotly import tools
  File "plotly/tools.py", line 22, in <module>
    from plotly.graph_objs import graph_objs
  File "plotly/graph_objs/__init__.py", line 12, in <module>
    from . graph_objs import (
  File "plotly/graph_objs/graph_objs.py", line 29, in <module>
    from plotly.graph_objs import graph_objs_tools
  File "plotly/graph_objs/graph_objs_tools.py", line 12, in <module>
    "Looks like you're running Python 2.6. Plotly expects newer "
ImportError: Looks like you're running Python 2.6. Plotly expects newer standard library versions of ordereddict and json. You can simply upgrade with these 'extras' with the following terminal command:
pip install 'plotly[PY2.6]'
$ pip install 'plotly[PY2.6]'  > /dev/null
$ python -c 'import plotly'
$ 
```

**Comment by scjody** [comment]
sweet, :dancer:

**Comment by scjody** [comment]
This hit another user.  Can you :dancer: this soon?

**Comment by theengineear** [comment]
@scjody , yup. Thanks!

**Pull request merged**
