### PR TITLE
sync chunked_requests after chriddyp/chunked_requests#5 merge 62581cf3a1 and address #324

### PR DESCRIPTION
**Pull request by kiwiroy**
looks correct, though I modified URLs in `.gitmodules` as I can not connect GitHub otherwise :blush:

### CODE REVIEW

**Comment by chriddyp** [comment]
@theengineear - look right to you?

**Comment by kiwiroy** [comment]
I'm happy to revert the `.gitmodules` change for convenience.

**Comment by theengineear** [comment]
The call to `make` should have made actual code changes in `plotly/plotly/chunked_requests`. In order to make it simpler for contributors (or this was the intent), we actually keep the code inside the python-api repo as a synced copy.

So, yeah, the changes in there look right, but you should have a bunch more code changes.

**Comment by kiwiroy** [comment]
@theengineear, that makes sense, and should be achieved by 4f8186e.

**Comment by theengineear** [comment]
:+1: lookin' good now! Thanks @kiwiroy!

**Pull request merged**
