### PR TITLE
Widgets save graph

### PR DESCRIPTION
**Pull request by theengineear**
Some annoyingly-implemented save functionality.

You can just call `graph.save(filename='whatevs')`. We might want the save call signature to match py.plot, not sure.

### CODE REVIEW

**Comment by theengineear** [comment]
@chriddyp , wanna give it a look? when this PR is merged, it'll work: https://github.com/plotly/streambed/pull/1192

**Comment by theengineear** [comment]
@chriddyp , I was making the tutorial for widgets, when i realized we never merged this guy in. should i fix it up and we can finally let users save graphs made in widgets : )

**Comment by chriddyp** [comment]
yeah, that sounds good

**Comment by theengineear** [comment]
cool, i'll try and fix it up tonight.

**Comment by theengineear** [comment]
@chriddyp , want to take a peek? I added the fadeTo functionality interface on top of the message protocol. A little sloppy maybe? I'm less familiar with how the messaging works though, so there may be a cleaner way.

**Comment by theengineear** [comment]
Note, there seems to be an issue in Python 2.6 with requests where requests[security] needs to be installed (so, beyond just requests). Perhaps a change in circle caused this to pop up? Should be fixed by the last two commits.

**Comment by chriddyp** [comment]
:dancer:

**Pull request merged**
